feat: refactor negative parsing test suite
isa-group/Pricing4Java pull request #25
Opened 2024-12-27 11:06 UTC by pgmarc

- Add script to merge negative cases csv `MergeCSV.java`
- Remove extra csv files and add a general negative-cases.csv file
- Some tests cases were not passing but commented them
- Add extra test case for addOn.dependsOn and addOn.availableFor
- Positive test suite not yet clean

2024-12-29 16:22 UTC, Alex-GF commented
Good job! Just a couple of things I’d like to ask you before merging:

1. I noticed that all the tests are negative cases, and the test suites with positive tests are brief and, in most cases, have tests with similar assertions hardcoded. Could you also transfer the positive tests from Pricing4TS to this repository in order to improve the robustness of the suite?
2. Could you remove the `MergeCSV.java` script from the library before merging? While it was useful for completing this task more quickly, it won’t add value to the library in the future, will it?
3. Is it possible to add a “test_name” field or something similar to all CSVs, like those in Pricing4TS, in order to assign a name to each of the tests generated by the parameterized test? With this approach, if a test fails, we can pinpoint exactly which one is causing the issue. Right now, it seems that it would just indicate that the parameterized test has failed, but not which execution caused it.

Looking forward to your responses and changes before merging. 😉

2024-12-29 16:22 UTC, Alex-GF requested changes
Good job! Just a couple of things I’d like to ask you before merging:

1. I noticed that all the tests are negative cases, and the test suites with positive tests are brief and, in most cases, have tests with similar assertions hardcoded. Could you also transfer the positive tests from Pricing4TS to this repository in order to improve the robustness of the suite?
2. Could you remove the `MergeCSV.java` script from the library before merging? While it was useful for completing this task more quickly, it won’t add value to the library in the future, will it?
3. Is it possible to add a “test_name” field or something similar to all CSVs, like those in Pricing4TS, in order to assign a name to each of the tests generated by the parameterized test? With this approach, if a test fails, we can pinpoint exactly which one is causing the issue. Right now, it seems that it would just indicate that the parameterized test has failed, but not which execution caused it.

Looking forward to your responses and changes before merging. 😉

2024-12-31 13:06 UTC, pgmarc commented
@Alex-GF 
- I have figured out how to pretty report tests in CI. Turns out that maven-surefire test reporter is uggly by default so I have to add a third party dependency to pretty print tests. The info is in this [link](https://medium.com/wearewaes/my-journey-to-a-clear-test-output-in-maven-df82fe272249)
 
If like the solution I will do it in a separate branch

2025-01-08 11:16 UTC, Alex-GF approved these changes
Perfect! Great job!

2025-01-08 11:18 UTC, merged